create table PAIS (id number primary key,
NOME VARCHAR2(20));

CREATE TABLE ESTADO (ID_ESTADO NUMBER PRIMARY, 
    NOME VARCHAR2(30),
    ID_PAIS NUMBER);
    
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO 
FOREIGN KEY (ID_PAIS) REFERENCE PAIS (ID_PAIS);

CREATE TABLE BAIRRO (ID_BAIRRO NUMBER, 
        NOME VARCHAR2(30),
        ID_CIDADE NUMBER);
    
ALTER TABLE CIDADE ADD CONSTRAINT FK_BAIRRO
FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE)

CREATE TABLE ENDERECO_CLIENTE(ID_CLIENTE NUMBER,
    NOME VARCHAR2(100),
    CEP VARCHAR2(12)
    ID_BAIRRO NUMBER);
    
ALTER TABLE ENDERECO_CLIENTE ADD constraint FK_END_CLIENTE
FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (ID_BAIRRO);